# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20170728_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='likecomm',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app1.PostModel'),
        ),
    ]
