# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_likecomm_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likecomm',
            name='post',
        ),
    ]
